apiVersion: v1
kind: Pod
metadata:
  name: myapp-backend-pod
  labels:
    app: myapp
    type: back-end

spec:
  containers:
    - name: backend
      image: backend
      env:
      - name: CONNECTION_STRING
        value: "postgres://demo_user:demo_user@db/demo_db"