apiVersion: v1
kind: Pod
metadata:
  name: myapp-db-pod
  labels:
    app: myapp
    type: db

spec:
  containers:
    - name: backend
      image: postgres:11.2-alpine
      env:
      - name: POSTGRES_USER
        value: "demo_user"
      - name: POSTGRES_PASSWORD
        value: "demo_user"
      - name: POSTGRES_DB
        value: demo_db