apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: myapp
    type: front-end

spec:
  containers:
    - name: frontend
      image: 821503567974.dkr.ecr.eu-west-1.amazonaws.com/frontend:2
      env:
      - name: API_URL
        value: "http://api:3001/data"
  imagePullSecrets:
  - name: regcred