apiVersion: v1
kind: Service
metadata: 
  name: web-service

spec:
  type: NodePort
  ports:
    - targetport: 3000
      port: 3000
      nodePort: 30008
  
  selector:
    app: myapp
    type: front-end
